-- nyaa.export -- renders the *same* palette nyaa.wear()/nyaa.palette()
-- use into config snippets for the rest of your desktop, the same job
-- catppuccin-styles does standalone (cli.py -> templates.py's
-- tmpl.get(target)(palette, ...) registry), just Lua-native and living
-- inside uwuwm's own config instead of a separate wallpaper-driven CLI
-- run. Nothing here touches uwu.set()/the compositor at all -- it's pure
-- string rendering plus (optionally) writing the result to disk, so it
-- composes with either workflow: call nyaa.export.render() and paste the
-- result yourself, or nyaa.export.write() to have rc.lua keep a target
-- file in sync with whatever nyaa.wear({flavor = ...}) picked, every
-- reload.
--
-- Every renderer takes a palette table shaped like palettes.lua's
-- (role name -> "#rrggbb") -- nyaa.export.render("kitty", "catppuccin_mocha")
-- resolves a name through nyaa.palette() for you; passing a raw table
-- (your own custom palette, or one hand-edited from a preset) works
-- identically.

local palettes_mod = require('nyaa.palettes')

local export = {}

-- ── helpers ──────────────────────────────────────────────────────────────

local function strip_hash(hex)
  return (hex:gsub('^#', ''))
end

local function resolve(palette)
  if type(palette) == 'string' then
    local p = palettes_mod[palette]
    if not p then
      local names = {}
      for name in pairs(palettes_mod) do
        table.insert(names, name)
      end
      table.sort(names)
      error(
        "nyaa.export: unknown palette '"
          .. palette
          .. "' (known: "
          .. table.concat(names, ', ')
          .. ')'
      )
    end
    return p
  end
  if type(palette) == 'table' then
    return palette
  end
  error('nyaa.export: palette must be a name (string) or a role table')
end

-- Catppuccin's own canonical ANSI-16 assignment (github.com/catppuccin/
-- catppuccin's "Standard ANSI Colors" table) -- reused verbatim for every
-- flavor/palette here so kitty/foot both get the same 16-color mapping
-- regardless of which palette table is behind it.
local ANSI16 = {
  { 'color0', 'surface1' },
  { 'color1', 'red' },
  { 'color2', 'green' },
  { 'color3', 'yellow' },
  { 'color4', 'blue' },
  { 'color5', 'pink' },
  { 'color6', 'teal' },
  { 'color7', 'subtext1' },
  { 'color8', 'surface2' },
  { 'color9', 'red' },
  { 'color10', 'green' },
  { 'color11', 'yellow' },
  { 'color12', 'blue' },
  { 'color13', 'pink' },
  { 'color14', 'teal' },
  { 'color15', 'subtext0' },
}

-- ── renderers ────────────────────────────────────────────────────────────
-- Each takes a resolved palette table and returns one string. Registered
-- under export.targets below by name -- add a renderer + one line there
-- to support a new target.

local function render_gtk_css(p)
  -- Drop straight into ~/.config/gtk-3.0/gtk.css or ~/.config/gtk-4.0/
  -- gtk.css (or @import it from an existing one) -- same @define-color
  -- convention Catppuccin's own GTK themes use, so any stylesheet that
  -- already references @accent_color/@window_bg_color-style names can be
  -- pointed at these instead.
  local lines = { '/* generated by nyaa.export -- do not hand-edit */' }
  local order = {
    'rosewater',
    'flamingo',
    'pink',
    'mauve',
    'red',
    'maroon',
    'peach',
    'yellow',
    'green',
    'teal',
    'sky',
    'sapphire',
    'blue',
    'lavender',
    'text',
    'subtext1',
    'subtext0',
    'overlay2',
    'overlay1',
    'overlay0',
    'surface2',
    'surface1',
    'surface0',
    'base',
    'mantle',
    'crust',
  }
  for _, role in ipairs(order) do
    table.insert(lines, '@define-color ' .. role .. ' ' .. p[role] .. ';')
  end
  return table.concat(lines, '\n') .. '\n'
end

local function render_kitty(p)
  local lines = {
    '# generated by nyaa.export -- do not hand-edit',
    'background            ' .. p.base,
    'foreground            ' .. p.text,
    'cursor                ' .. p.rosewater,
    'cursor_text_color     ' .. p.base,
    'url_color             ' .. p.rosewater,
    'selection_background  ' .. p.text,
    'selection_foreground  ' .. p.base,
    'active_border_color   ' .. p.mauve,
    'inactive_border_color ' .. p.overlay0,
    'active_tab_background ' .. p.mauve,
    'active_tab_foreground ' .. p.base,
  }
  for _, pair in ipairs(ANSI16) do
    table.insert(lines, pair[1] .. (' '):rep(15 - #pair[1]) .. p[pair[2]])
  end
  return table.concat(lines, '\n') .. '\n'
end

local function render_foot(p)
  -- foot.ini's [colors] section wants bare RRGGBB, no leading '#', and
  -- foreground/background as their own keys rather than color0/color7's
  -- job the way kitty does it.
  local lines = {
    '; generated by nyaa.export -- do not hand-edit',
    '[colors]',
    'foreground=' .. strip_hash(p.text),
    'background=' .. strip_hash(p.base),
  }
  for _, pair in ipairs(ANSI16) do
    table.insert(lines, pair[1] .. '=' .. strip_hash(p[pair[2]]))
  end
  return table.concat(lines, '\n') .. '\n'
end

local function render_waybar(p)
  -- CSS custom properties, meant to be @import-ed at the top of waybar's
  -- style.css ahead of rules that reference var(--mauve) etc -- same role
  -- names as the GTK renderer above, just CSS-custom-property instead of
  -- @define-color syntax, since waybar's GTK-CSS subset doesn't resolve
  -- @define-color the way a real GTK app does.
  local lines =
    { '/* generated by nyaa.export -- do not hand-edit */', ':root {' }
  local order = {
    'rosewater',
    'flamingo',
    'pink',
    'mauve',
    'red',
    'maroon',
    'peach',
    'yellow',
    'green',
    'teal',
    'sky',
    'sapphire',
    'blue',
    'lavender',
    'text',
    'subtext1',
    'subtext0',
    'overlay2',
    'overlay1',
    'overlay0',
    'surface2',
    'surface1',
    'surface0',
    'base',
    'mantle',
    'crust',
  }
  for _, role in ipairs(order) do
    table.insert(lines, '  --' .. role .. ': ' .. p[role] .. ';')
  end
  table.insert(lines, '}')
  return table.concat(lines, '\n') .. '\n'
end

local function render_dunst(p)
  -- A dunstrc fragment, not a full config -- meant to sit under your own
  -- [global]/[urgency_*] sections (or be #include-d, if your dunst build
  -- supports it) so geometry/timeout/etc stay hand-written while colors
  -- track the palette.
  local lines = {
    '# generated by nyaa.export -- do not hand-edit',
    '[urgency_low]',
    'background = "' .. p.base .. '"',
    'foreground = "' .. p.text .. '"',
    'frame_color = "' .. p.surface0 .. '"',
    '',
    '[urgency_normal]',
    'background = "' .. p.base .. '"',
    'foreground = "' .. p.text .. '"',
    'frame_color = "' .. p.mauve .. '"',
    '',
    '[urgency_critical]',
    'background = "' .. p.base .. '"',
    'foreground = "' .. p.text .. '"',
    'frame_color = "' .. p.red .. '"',
  }
  return table.concat(lines, '\n') .. '\n'
end

-- name -> { render = fn(palette) -> string, filename = default basename }
export.targets = {
  gtk3 = { render = render_gtk_css, filename = 'gtk-3.0-colors.css' },
  gtk4 = { render = render_gtk_css, filename = 'gtk-4.0-colors.css' },
  kitty = { render = render_kitty, filename = 'kitty-colors.conf' },
  foot = { render = render_foot, filename = 'foot-colors.ini' },
  waybar = { render = render_waybar, filename = 'waybar-colors.css' },
  dunst = { render = render_dunst, filename = 'dunstrc-colors' },
}

-- nyaa.export.render("kitty", "catppuccin_mocha")
-- nyaa.export.render("gtk3", nyaa.palette("catppuccin_mocha"))
--
-- `palette` is either a name known to nyaa.palettes, or a raw role table
-- (nyaa.palette()'s return shape) -- so a hand-tweaked copy works exactly
-- like a preset name does.
function export.render(target, palette)
  local t = export.targets[target]
  if not t then
    local names = {}
    for name in pairs(export.targets) do
      table.insert(names, name)
    end
    table.sort(names)
    error(
      "nyaa.export.render: unknown target '"
        .. tostring(target)
        .. "' (known: "
        .. table.concat(names, ', ')
        .. ')'
    )
  end
  return t.render(resolve(palette))
end

-- nyaa.export.write("kitty", "/home/jless/.config/kitty/colors-uwuwm.conf", "catppuccin_mocha")
--
-- Writes the rendered string to `path` (parent directory must already
-- exist -- this never mkdir -p's on your behalf). Returns true, or nil +
-- an error message on an io.open/write failure, same convention
-- io.open() itself uses -- so `local ok, err = nyaa.export.write(...)`
-- reads naturally in rc.lua without wrapping every call in pcall.
function export.write(target, path, palette)
  local body = export.render(target, palette)
  local fh, err = io.open(path, 'w')
  if not fh then
    return nil, err
  end
  fh:write(body)
  fh:close()
  return true
end

-- nyaa.export.write_all("/home/jless/.cache/uwuwm-theme", "catppuccin_mocha")
-- nyaa.export.write_all(dir, palette, { "kitty", "waybar" }) -- subset only
--
-- One call to refresh every target's file in `dir` at once (each target's
-- own export.targets[name].filename), e.g. from a paw.on("focuses", ...)
-- hook or just once at the bottom of rc.lua after nyaa.wear(). Returns a
-- table of { [target] = true|nil } and, for any that failed, a second
-- table of { [target] = err }.
function export.write_all(dir, palette, only)
  local list = {}
  if only then
    list = only
  else
    for name in pairs(export.targets) do
      table.insert(list, name)
    end
    table.sort(list)
  end

  local ok, errors = {}, {}
  for _, target in ipairs(list) do
    local t = export.targets[target]
    if not t then
      errors[target] = 'unknown target'
    else
      local success, err =
        export.write(target, dir .. '/' .. t.filename, palette)
      if success then
        ok[target] = true
      else
        errors[target] = err
      end
    end
  end
  return ok, errors
end

return export
